### PR TITLE
Add Json format for the type popup button

### PR DESCRIPTION
**Pull request by lahmho**

### CODE REVIEW

**Comment by lamho** [comment]
Hi,

Please review it

**Comment by jfahrenkrug** [comment]
Hi,

Thank you for your PR, sorry for taking so long to get back to you. Could you explain the changes in the xib file? I only see over 2000 deletions. Maybe you can add a few explanations?

Thank you!

- Johannes

**Comment by lamho** [comment]
Hi Johannes,

I only add json format in the type combobox of the xib files. Also adding code to support json format in .m files.

Thank you,
Lam

**Comment by lamho** [comment]
Hi Jfahrenkrug,

Nothing changes in .xib file except I add "Json" in style popup button. Other changes is from auto format of xcode. 

Thank you,
Lam

**Comment by jfahrenkrug** [comment]
Hi Lam,

Thank you very much, I'll take a look very soon! Thanks for your help!

Johannes

**Pull request closed without merging**
